"""Generate a real, text-searchable FIR PDF.

The generated bytes are a PDF document produced by ReportLab, not HTML saved
with a .pdf extension. Text is written as PDF text objects so PyMuPDF/native
extraction can read it later for Case AI.
"""
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from xml.sax.saxutils import escape


def _text(value) -> str:
    return escape(str(value if value is not None else ""))


def generate_fir_pdf(
    *,
    fir_number: str,
    filed_at: str,
    filed_by: str,
    employee_id: str,
    department: str,
    complainant_name: str,
    incident_type: str,
    incident_date: str,
    location: str,
    description: str,
) -> bytes:
    """Return valid, searchable PDF bytes containing the submitted FIR data."""
    out = BytesIO()
    doc = SimpleDocTemplate(
        out,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=f"FIR {fir_number}",
        author="Secure DMS",
    )

    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "FIRTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=17,
        leading=21,
        spaceAfter=14,
    )
    label = ParagraphStyle(
        "FIRLabel",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=13,
    )
    body = ParagraphStyle(
        "FIRBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        spaceAfter=5,
    )
    small = ParagraphStyle(
        "FIRSmall",
        parent=body,
        fontSize=8.5,
        leading=12,
    )

    story = [
        Paragraph("FIRST INFORMATION REPORT", title),
        Paragraph(f"<b>FIR Number:</b> {_text(fir_number)}", body),
        Paragraph(f"<b>Date and Time Filed:</b> {_text(filed_at)}", body),
        Paragraph(f"<b>Filed By:</b> {_text(filed_by)}", body),
        Paragraph(f"<b>Employee ID:</b> {_text(employee_id)}", body),
        Paragraph(f"<b>Department:</b> {_text(department)}", body),
        Spacer(1, 8),
    ]

    rows = [
        [Paragraph("Particular", label), Paragraph("Details", label)],
        [Paragraph("Complainant Name", label), Paragraph(_text(complainant_name), body)],
        [Paragraph("Incident Type", label), Paragraph(_text(incident_type), body)],
        [Paragraph("Incident Date", label), Paragraph(_text(incident_date), body)],
        [Paragraph("Location", label), Paragraph(_text(location), body)],
    ]
    table = Table(rows, colWidths=[48 * mm, 122 * mm], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story += [table, Spacer(1, 12)]
    story += [Paragraph("Description", label), Paragraph(_text(description), body)]
    story += [
        Spacer(1, 18),
        Paragraph("Digital Filing Record", label),
        Paragraph(
            "This FIR was generated by Secure DMS from the submitted form. "
            "The original PDF bytes are SHA-256 hashed and digitally signed "
            "with the filing user's RSA-3072 key using RSA-PSS/SHA-256.",
            small,
        ),
        Spacer(1, 18),
        Paragraph(f"<b>Digital Signatory:</b> {_text(filed_by)} ({_text(employee_id)})", small),
        Paragraph(f"<b>Signed/Filed At:</b> {_text(filed_at)}", small),
    ]

    doc.build(story)
    data = out.getvalue()
    if not data.startswith(b"%PDF-"):
        raise RuntimeError("FIR generator did not produce a valid PDF.")
    return data
